DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS animal;

CREATE TABLE students(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
fio VARCHAR(256),
age INT
);

CREATE TABLE animal(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
vie VARCHAR(256),
wei INT
);
